/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gameproject;

/**
 *
 * @author Amind
 */
public class GameView extends javax.swing.JFrame {
    private String value1;
    private String value2;
    private String value3;
    private String value4;
    private String value5;
    private String value6;
    private String value7;
    private String value8;
    private String value9;
    /**
     * Creates new form GameView
     */
    public GameView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Tic-Tac-Toe");
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 6, 333, 30));

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Player X");
        lblName.setOpaque(true);
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 48, 91, 35));

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 372, -1, -1));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 91, 91));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 91, 91));

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 91, 91));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 91, 91));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 91, 91));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 91, 91));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 91, 91));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 91, 91));

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 91, 91));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       int index = 2;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn2.setText("X");
           btn2.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn2.setText("O");
           btn2.setEnabled(false);
       }
       value2 = btn2.getText();
       if(value2.equals(value1)&value2.equals(value3)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value2.equals(value5)&value2.equals(value8)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       int index = 1;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn1.setText("X");
           btn1.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn1.setText("O");
           btn1.setEnabled(false);
       }
       value1 = btn1.getText();
       if(value1.equals(value2)&value1.equals(value3)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value1.equals(value4)&value1.equals(value7)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value1.equals(value5)&value1.equals(value9)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
       int index = 3;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn3.setText("X");
           btn3.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn3.setText("O");
           btn3.setEnabled(false);
       }
       value3 = btn3.getText();
       if(value3.equals(value2)&value1.equals(value1)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value3.equals(value6)&value3.equals(value9)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value3.equals(value5)&value3.equals(value7)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
       int index = 4;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn4.setText("X");
           btn4.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn4.setText("O");
           btn4.setEnabled(false);
       }
       value4 = btn4.getText();
       if(value4.equals(value5)&value4.equals(value6)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value4.equals(value1)&value4.equals(value7)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       int index = 5;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn5.setText("X");
           btn5.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn5.setText("O");
           btn5.setEnabled(false);
       }
       value5 = btn5.getText();
       if(value5.equals(value1)&value5.equals(value9)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value5.equals(value2)&value5.equals(value8)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value5.equals(value3)&value5.equals(value7)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value5.equals(value4)&value5.equals(value6)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       int index = 6;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn6.setText("X");
           btn6.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn6.setText("O");
           btn6.setEnabled(false);
       }
       value6 = btn6.getText();
       if(value6.equals(value3)&value6.equals(value9)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value6.equals(value4)&value6.equals(value5)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
       int index = 7;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn7.setText("X");
           btn7.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn7.setText("O");
           btn7.setEnabled(false);
       }
       value7 = btn7.getText();
       if(value7.equals(value4)&value7.equals(value1)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value7.equals(value8)&value7.equals(value9)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value7.equals(value5)&value7.equals(value3)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
       int index = 8;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn8.setText("X");
           btn8.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn8.setText("O");
           btn8.setEnabled(false);
       }
       value8 = btn8.getText();
        if(value8.equals(value7)&value8.equals(value9)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value8.equals(value5)&value8.equals(value2)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
       int index = 9;
       if("Player X".equals(lblName.getText())){
           lblName.setText("Player O");
           btn9.setText("X");
           btn9.setEnabled(false);
       }else{
           lblName.setText("Player X");
           btn9.setText("O");
           btn9.setEnabled(false);
       }
       value9 = btn9.getText();
       if(value9.equals(value8)&value9.equals(value7)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value9.equals(value5)&value9.equals(value1)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }else if(value9.equals(value6)&value9.equals(value3)){
           lblName.setText("Won");
           btn1.setEnabled(false);
           btn2.setEnabled(false);
           btn3.setEnabled(false);
           btn4.setEnabled(false);
           btn5.setEnabled(false);
           btn6.setEnabled(false);
           btn7.setEnabled(false);
           btn8.setEnabled(false);
           btn9.setEnabled(false);
       }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        btn1.setText("");
        btn1.setEnabled(true);
        btn2.setText("");
        btn2.setEnabled(true);
        btn3.setText("");
        btn3.setEnabled(true);
        btn4.setText("");
        btn4.setEnabled(true);
        btn5.setText("");
        btn5.setEnabled(true);
        btn6.setText("");
        btn6.setEnabled(true);
        btn7.setText("");
        btn7.setEnabled(true);
        btn8.setText("");
        btn8.setEnabled(true);
        btn9.setText("");
        btn9.setEnabled(true);
        lblName.setText("Player X");
        
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GameView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
